# Generated by Django 5.1.6 on 2025-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Text', 'Text'), ('File', 'File')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('OnlyMe', 'OnlyMe'), ('Subscribers', 'Subscribers'), ('Public', 'Public')], default='OnlyMe', max_length=20)),
            ],
        ),
    ]
