# Generated by Django 5.1.6 on 2025-02-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='content_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('OnlyMe', 'OnlyMe'), ('Subscribers', 'Subscribers'), ('Public', 'Public')], default='OnlyMe', max_length=15),
        ),
    ]
