# Generated by Django 5.1.6 on 2025-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rename_created_at_content_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='date',
            new_name='created_at',
        ),
    ]
