# Generated by Django 5.1.6 on 2025-02-21 12:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_content_description_alter_content_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='created_at',
        ),
        migrations.AddField(
            model_name='content',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('text', 'Text'), ('file', 'File')], max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('onlyme', 'Only Me'), ('subscribers', 'Subscribers'), ('public', 'Public')], default='onlyme', max_length=20),
        ),
    ]
